---

hibernate:
    cache:
      queries: false
      use_second_level_cache: true
      use_query_cache: false
      region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'
    hbm2ddl:
      auto: none

---
grails:
    profile: rest-api
    codegen:
        defaultPackage: com.wwt.itemuploadapi
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:

    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---
environments:
  development:
    configserver:
      url: https://config-api.apps-local.wwt.com
      username: apps
      password: d3vconfig!

    wwt.security.permissions.optional: true

    server:
      contextPath: '/item-upload-api'
