CREATE OR REPLACE TYPE APPS.WWT_ITEM_CREATION_RECTYPE IS OBJECT
(segment2         VARCHAR2(40),
 segment3         VARCHAR2(40),
 segment1         VARCHAR2(40),
 segment4         VARCHAR2(40),
 organization_code VARCHAR2(3),
 transaction_type VARCHAR2(10),
 description      VARCHAR2(240),
 primary_uom_code VARCHAR2(3),
 serial_number_control_code NUMBER,
 template_id      NUMBER,
 attribute1       VARCHAR2(240),
 attribute15      VARCHAR2(240),

 CONSTRUCTOR FUNCTION WWT_ITEM_CREATION_RECTYPE RETURN SELF AS RESULT
);
/

CREATE OR REPLACE SYNONYM WL_USER.WWT_ITEM_CREATION_RECTYPE FOR APPS.WWT_ITEM_CREATION_RECTYPE;


GRANT EXECUTE ON APPS.WWT_ITEM_CREATION_RECTYPE TO CF_TEMP_ROLE;

GRANT EXECUTE ON APPS.WWT_ITEM_CREATION_RECTYPE TO WL_USER;